### PR TITLE
Fibonacci-series.c

### PR DESCRIPTION
**Pull request by Znis**

### CODE REVIEW

**Comment by thenishantsapkota** [comment]
Rename the file to `fibonacci-series.c`

**Comment by PrajwalCH** [comment]
Isn't pull requesting different project/program on same language not allowed by one user?

**Comment by thenishantsapkota** [comment]
> Isn't pull requesting different project/program on same language not allowed by same user?

You can do it, as some people may not know more than one language 😄

**Comment by PrajwalCH** [comment]
> > Isn't pull requesting different project/program on same language not allowed by same user?
> 
> You can do it, as some people may not know more than one language 😄

Oh ok. I thought it's not allowed 😁

**Comment by thenishantsapkota** [comment]
> > > Isn't pull requesting different project/program on same language not allowed by same user?
> > 
> > 
> > You can do it, as some people may not know more than one language 😄
> 
> Oh ok. I thought it's not allowed 😁

You can do that!
Happy Hacktoberfest 😄

**Comment by PrajwalCH** [comment]
> > > > Isn't pull requesting different project/program on same language not allowed by same user?
> > > 
> > > 
> > > You can do it, as some people may not know more than one language 😄
> > 
> > 
> > Oh ok. I thought it's not allowed 😁
> 
> You can do that! Happy Hacktoberfest 😄

Thank you ☺️

**Pull request merged**
