### PR TITLE
Different Linked Lists with Functionality Added

### PR DESCRIPTION
**Pull request by souvikpal2000**
Different Types of Linked List like Singly, Doubly, Circular & Circular Doubly added. 
Thank You for giving us a chance to contribute to your Repository.

### CODE REVIEW

**Comment by thenishantsapkota** [comment]
Instead of using spaces in the filename, Please consider using `_` or `-` to name the files.

**Comment by souvikpal2000** [comment]
Do I need to push one more time?

**Comment by thenishantsapkota** [comment]
> Do I need to push one more time?

Yes make the changes and update in the existing PR.

**Comment by souvikpal2000** [comment]
Done...!! 
Please add the label of "hacktoberfest-accepted"

**Comment by thenishantsapkota** [comment]
Merging the PR does the same thing.
I already merged the PR

**Comment by souvikpal2000** [comment]
Yes, but till now label section is blank for me.

**Comment by thenishantsapkota** [comment]
> Yes, but till now label section is blank for me.

As I said label and merging the PR does the same thing.
I have already merged your PR so there is no need for a label now.

**Comment by souvikpal2000** [comment]
Okay Sir,
This is my first time in contribution to open source.
Just to know, you have merged my commit with Main but not labelled as "hacktoberfest-accepted". I have seen other pull requests labelled as "hacktoberfest-accepted".
Will my contriburtion will be considered for hacktoberfest?

**Comment by thenishantsapkota** [comment]
image
🤷

**Comment by souvikpal2000** [comment]
Sir, I've checked my profile in Hacktoberfest.... It is showing that my Project is Excluded.

**Pull request merged**
