### PR TITLE
simple guessing game

### PR DESCRIPTION
**Pull request by karkigrishmin**

### CODE REVIEW

**Comment by PrajwalCH** [comment]
@karkigrishmin 
Please pull request per program.

**Comment by karkigrishmin** [comment]
> @karkigrishmin Please pull request per program.

**Comment by karkigrishmin** [comment]
> @karkigrishmin Please pull request per program.

I had created PRs for each program, idk how all the programs gets added in same each PR:(

**Comment by karkigrishmin** [comment]
@PrajwalCH Please tell me the solution, what should I do now?

**Comment by PrajwalCH** [comment]
@thenishantsapkota 
What can we do about this?

**Comment by thenishantsapkota** [comment]
> @thenishantsapkota What can we do about this?

Just put the `hacktoberfest-accepted` label for now.
I will look into this tommorow

**Comment by karkigrishmin** [comment]
@PrajwalCH just deleted all other program files.
I think now we can merge this PR.

**Pull request merged**
