### PR TITLE
dart textfield, name, password validator methods

### PR DESCRIPTION
**Pull request by aprashantz**
You can use this to validate password, email, name textfield for any of your flutter apps.

### CODE REVIEW

**Comment by PrajwalCH** [comment]
Return true if text is valid and false if not. That will be much easier to check return value of validators.

**Comment by aprashantz** [comment]
in flutter's textformfield validator, it should return null to take the user's input as valid, so, i did it that way.

**Comment by aprashantz** [comment]
> 
> 
> Return true if text is valid and false if not. That will be much easier to check return value of validators.

in flutter's textformfield validator, it should return null to take the user's input as valid, so, i did it that way.

**Comment by PrajwalCH** [comment]
Ah ok then

**Pull request merged**
