### PR TITLE
Added constructors and destructors in object oriented programming.

### PR DESCRIPTION
**Pull request by Shivam-Shrivastav**
Added a directory containing a code example of constructors and destructors in object oriented programming along with a their explanation in .md format.

### CODE REVIEW

**Comment by Shivam-Shrivastav** [comment]
Added Jarvis.py in Python directory

**Comment by PrajwalCH** [comment]
Make a separate pull request for python program.

**Comment by Shivam-Shrivastav** [comment]
Made a separate pull request ( #639 ) for Jarvis.py in python program.

**Comment by PrajwalCH** [comment]
Delete python program.

**Comment by Shivam-Shrivastav** [comment]
> Delete python program.

Sorry I can't because I have deleted the previously forked repo accidently.

**Pull request merged**
