### PR TITLE
Create download_PDF.py

### PR DESCRIPTION
**Pull request by ExtraOrdinaire1**

### CODE REVIEW

**Comment by ExtraOrdinaire1** [comment]
bro i request you to label it as hacktober challenge accepted

**Comment by thenishantsapkota** [comment]
Merging and giving `hacktoberfest-accepted` label does the same thing. 😄

**Review by thenishantsapkota — CHANGES_REQUESTED** [review]
Please use `_` or `-` in file names instead of spaces.
Do that and the PR will be merged. 😄

**Comment by ExtraOrdinaire1** [comment]
but still, in official website, it say zero total completed

**Comment by ExtraOrdinaire1** [comment]
I did update the filename

**Comment by thenishantsapkota** [comment]
> but still, in official website, it say zero total completed

The Hacktoberfest Website is currently broken due to the shear number of Pull Requests being made.

**Pull request merged**
