### PR TITLE
Implement The Game : Guess The Number.

### PR DESCRIPTION
**Pull request by bhavya-sarraf-26**
If merged, the pull request will add The Game : Guess The Number implemented in C++.

### CODE REVIEW

**Review by PrajwalCH — COMMENTED** [review]
You did incorrect.
Place the **srand(unsignedtime(0));**.

**Comment by bhavya-sarraf-26** [comment]
Is there any need to do that?
Because the line has been placed within a function used for generating a random number whenever called...

**Comment by PrajwalCH** [comment]
> Is there any need to do that? Because the line has been placed within a function used for generating a random number whenever called...

It's not necessary but it's good to called generator as soon as main is called.

**Comment by bhavya-sarraf-26** [comment]
Edited the code again.
Please check it.

**Pull request closed without merging**
