### PR TITLE
added palindrome.js and arrayadd.js

### PR DESCRIPTION
**Pull request by B0s0**
Two js code files: one to find palindrome number and another to add elements of two arrays simultaneously.

### CODE REVIEW

**Comment by dibashthapa** [comment]
Whats the file name `arrayadd.js` for ?

**Comment by B0s0** [comment]
it is another file that contains the code to add elements of two arrays simulatneously

**Comment by B0s0** [comment]
@dibashthapa  `arrayadd.js` is the file that contains the code to add elements of two arrays simultaneously.

**Comment by dibashthapa** [comment]
Please use `let` instead of var in js

**Comment by B0s0** [comment]
@dibashthapa  is it ok now?

**Comment by B0s0** [comment]
@dibashthapa  damn so sorry to trouble you but i mistakenly closed the pull request. so is it ok now ? i made some changes.

**Comment by B0s0** [comment]
@thenishantsapkota  any updates on this?

**Pull request closed without merging**
