### PR TITLE
A simple program to find the extension of a given file name

### PR DESCRIPTION
**Pull request by TheCoolGDev**
A simple js program to find the extension of the given file name and Happy Hacktober!

### CODE REVIEW

**Comment by PrajwalCH** [comment]
@TheCoolGDev 
What do you say about this?
`/home/.git`
Is `.git` as valid file name?

**Comment by TheCoolGDev** [comment]
i think it is not a valid file name as it needs to have some name before the extension

**Comment by TheCoolGDev** [comment]
@PrajwalCH I think it is a valid file name even though it has no name before its extension as it is accepted globally..

**Comment by PrajwalCH** [comment]
> @PrajwalCH I think it is a valid file name even though it has no name before its extension as it is accepted globally..

It's a hidden dir not a file name. Refactor your code so that it can handle hidden dir also.

**Pull request closed without merging**
