### PR TITLE
added joke fetcher

### PR DESCRIPTION
**Pull request by awebisam**

### CODE REVIEW

**Comment by awebisam** [comment]
@thenishantsapkota please add 'hacktoberfest-accepted' label on this PR. 
image

**Comment by thenishantsapkota** [comment]
@awebisam Should I not merge the PR?

**Comment by awebisam** [comment]
No, merge it. Also add the label.

**Comment by thenishantsapkota** [comment]
Label does the same thing as Merge

**Comment by awebisam** [comment]
Yes, it is. Just for safety reasons. 😁🤗

**Pull request merged**
