### PR TITLE
Added FrontEnd folder and Name Printer project

### PR DESCRIPTION
**Pull request by TheCoolGDev**
I have added a folder for Front end projects and my project named Name printer which was made using html css and js (basic).

### CODE REVIEW

**Comment by PrajwalCH** [comment]
@TheCoolGDev 
Make a folder for your project inside JavaScript-Programs and then make a pull request again.

**Comment by TheCoolGDev** [comment]
I told it to Nishant sir but he said me to make one folder for front end

**Comment by PrajwalCH** [comment]
Ah ok. But i think HTML will be good name for frontend projects.

**Comment by TheCoolGDev** [comment]
Oh Ok sir

**Pull request merged**
